// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyIQJJVZGywY2q2vZF34yeUbrSLku9_k4',
    appId: '1:251640364049:web:a0dc723cc087512ea9c5b0',
    messagingSenderId: '251640364049',
    projectId: 'crud-84715',
    authDomain: 'crud-84715.firebaseapp.com',
    storageBucket: 'crud-84715.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX--p-NGGNPf20YneKX36szWQhbqxH0-Y',
    appId: '1:251640364049:android:5ccb59ab79fbcde6a9c5b0',
    messagingSenderId: '251640364049',
    projectId: 'crud-84715',
    storageBucket: 'crud-84715.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO3uRMpeS4J2fjPnC8SlABj74GkrIvguw',
    appId: '1:251640364049:ios:f282eb15115e1062a9c5b0',
    messagingSenderId: '251640364049',
    projectId: 'crud-84715',
    storageBucket: 'crud-84715.appspot.com',
    iosClientId: '251640364049-qo1bm2rrtl594dgpikiodjgui3p3acks.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO3uRMpeS4J2fjPnC8SlABj74GkrIvguw',
    appId: '1:251640364049:ios:031c6f1b77681634a9c5b0',
    messagingSenderId: '251640364049',
    projectId: 'crud-84715',
    storageBucket: 'crud-84715.appspot.com',
    iosClientId: '251640364049-ns7sea2ivunfjvapdbn8bn427krfg42p.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud.RunnerTests',
  );
}
